swagger: '2.0'
info:
  description: Bookable service
  version: 1.0.0
  title: Bookable service
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: bookable.swagger.io
basePath: /v2
tags:
  - name: bookable
    description: Endpoints for bookables
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - http
paths:
  /bookables:
    get:
      tags:
        - bookable
      summary: Get list of bookables
      description: ''
      operationId: getBookables
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Bookable object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Bookable'
      responses:
        '405':
          description: Invalid input
  '/bookables/{bookableId}':
    get:
      tags:
        - bookable
      summary: Find bookable by ID
      description: Returns a single bookable
      operationId: getBookableById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: bookableId
          in: path
          description: ID of bookable to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bookable'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bookable not found
definitions:
  Bookable:
    type: object
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: hytte ved sjøen
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      status:
        type: string
        description: bookable status
        enum:
          - available
          - pending
          - sold
    xml:
      name: Bookable
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
